"""udev rule generator.

Generates `/etc/udev/rules.d/99-hive-<name>.rules` content that creates
stable /dev/<logical-name> symlinks for discovered devices.

Per ADR-0003 and the safety review, every device that HIVE will use
must be referenced by a STABLE path, not by /dev/ttyACM0 (kernel-assigned).

Rule format:
  SUBSYSTEM=="tty", ATTRS{idVendor}=="<vid>", ATTRS{idProduct}=="<pid>", ATTRS{serial}=="<serial>", SYMLINK+="hive/<logical-name>"

We match on (VID + PID + serial) — never VID+PID alone, because two
identical devices would fight over the symlink.

If serial is missing (some cheap clones), we fall back to:
  SUBSYSTEM=="tty", ATTRS{idVendor}=="<vid>", ATTRS{idProduct}=="<pid>", ENV{ID_PATH}=="<port-path>", SYMLINK+="hive/<logical-name>"

This is less stable (port-path can change with USB topology) but better
than nothing.

The rule is WRITTEN to disk by UdevRuleInstaller.install(), which
requires root (sudo). For test purposes, we expose generate() that
returns the rule text and install() that writes + reloads (only if
sudo is available).

Idempotency: install() overwrites the existing file. The user is
expected to inspect the generated content before applying.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from hive.common.errors import HiveError
from hive.discovery.models import DiscoveredDevice


class UdevError(HiveError):
    """Raised when udev rule generation/install fails."""


@dataclass(frozen=True)
class UdevRule:
    """One udev SYMLINK rule.

    `subsystem` is always "tty" in H1 (we only symlink serial ports).
    """

    vid: str
    pid: str
    serial: str | None
    port_path: str | None
    logical_name: str
    description: str | None = None

    def render(self) -> str:
        """Render the rule text (single line, with optional comment)."""
        comment = (
            f"# HIVE auto-generated — {self.description}"
            if self.description
            else "# HIVE auto-generated"
        )

        # Match on VID + PID first
        match_parts = [
            'SUBSYSTEM=="tty"',
            f'ATTRS{{idVendor}}=="{self.vid}"',
            f'ATTRS{{idProduct}}=="{self.pid}"',
        ]

        # Prefer serial-based matching (most stable).
        if self.serial:
            # Quote-escape the serial number to avoid breaking the rule.
            # udev uses double-quote strings; backslash-escape is required.
            safe_serial = self.serial.replace("\\", "\\\\").replace('"', '\\"')
            match_parts.append(f'ATTRS{{serial}}=="{safe_serial}"')
        elif self.port_path:
            # Fallback to USB port path (less stable but better than nothing).
            match_parts.append(f'ENV{{ID_PATH}}=="{self.port_path}"')
        else:
            # No serial, no port path — can't safely match.
            return f"{comment}\n# SKIPPED: device has no serial and no port_path\n"

        match_parts.append(f'SYMLINK+="hive/{self.logical_name}"')
        return f"{comment}\n{', '.join(match_parts)}\n"


class UdevRuleInstaller:
    """Generates and optionally installs udev rules.

    Default install path: /etc/udev/rules.d/99-hive.rules
    """

    DEFAULT_PATH = Path("/etc/udev/rules.d/99-hive.rules")

    def __init__(self, *, install_path: Path | None = None) -> None:
        self.install_path = install_path if install_path is not None else self.DEFAULT_PATH

    @staticmethod
    def generate(
        devices: list[DiscoveredDevice],
        *,
        name_map: dict[str, str] | None = None,
    ) -> str:
        """Generate udev rules for the given devices.

        Args:
            devices: discovered devices with vid+pid.
            name_map: optional mapping fingerprint -> logical name.
                     If a device is not in the map, a default name is
                     generated from VID:PID.

        Returns:
            The full rules text (multi-line string).
        """
        rules: list[str] = []
        rules.append(
            "# Auto-generated by HIVE discovery — DO NOT EDIT BY HAND.\n"
            "# Regenerate with: hive device install-udev-rules\n"
            "# Reload with: sudo udevadm control --reload-rules && sudo udevadm trigger\n"
        )

        for dev in devices:
            if dev.usb_vid is None or dev.usb_pid is None:
                # Cannot create a stable rule without VID/PID
                continue

            logical_name = (name_map or {}).get(dev.fingerprint)
            if logical_name is None:
                # Default: hive/<vid>-<pid>-<serial-or-port>
                serial_part = dev.serial_number or (dev.usb_port_path or "unknown").replace(
                    "/", "-"
                ).replace(".", "-")
                logical_name = f"{dev.usb_vid}-{dev.usb_pid}-{serial_part}"

            rule = UdevRule(
                vid=dev.usb_vid,
                pid=dev.usb_pid,
                serial=dev.serial_number,
                port_path=dev.usb_port_path,
                logical_name=logical_name,
                description=dev.description or dev.product or dev.manufacturer,
            )
            rules.append(rule.render())

        return "".join(rules)

    def install(self, rules_text: str) -> None:
        """Write rules to disk. Requires root in production.

        For tests, pass a custom install_path that points to a tmp dir.
        """
        try:
            self.install_path.parent.mkdir(parents=True, exist_ok=True)
            self.install_path.write_text(rules_text)
        except PermissionError as e:
            raise UdevError(
                f"Cannot write {self.install_path}: permission denied. "
                "Re-run with sudo or set a custom install_path.",
                details={"path": str(self.install_path)},
            ) from e
        except OSError as e:
            raise UdevError(
                f"Cannot write {self.install_path}: {e}",
                details={"path": str(self.install_path)},
            ) from e
