"""CLI tests for H1 device commands (scan, register, db-list, install-udev-rules).

Uses HIVE_DB_URL=sqlite:///:memory: so no real DB is touched.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from typer.testing import CliRunner

from hive.cli.main import app


@pytest.fixture
def runner() -> CliRunner:
    return CliRunner()


@pytest.fixture
def mem_env(monkeypatch):
    """Use an in-memory SQLite DB for the CLI invocations."""
    monkeypatch.setenv("HIVE_DB_URL", "sqlite:///:memory:")


class TestDeviceScanCli:
    def test_scan_runs(self, runner: CliRunner, mem_env) -> None:
        res = runner.invoke(app, ["device", "scan", "--no-persist", "--no-usb", "--no-serial"])
        assert res.exit_code == 0
        assert "Scanned 0 device(s)" in res.stdout

    def test_scan_json_output(self, runner: CliRunner, mem_env) -> None:
        import json

        res = runner.invoke(
            app,
            ["device", "scan", "--no-persist", "--no-usb", "--no-serial", "--json"],
        )
        assert res.exit_code == 0
        data = json.loads(res.stdout)
        assert "scanned" in data
        assert "devices" in data


class TestDeviceDbListCli:
    def test_db_list_empty(self, runner: CliRunner, mem_env) -> None:
        res = runner.invoke(app, ["device", "db-list"])
        assert res.exit_code == 0
        assert "No devices" in res.stdout

    def test_db_list_json_empty(self, runner: CliRunner, mem_env) -> None:
        import json

        res = runner.invoke(app, ["device", "db-list", "--json"])
        assert res.exit_code == 0
        data = json.loads(res.stdout)
        assert data["devices"] == []


class TestDeviceRegisterCli:
    def test_register_unknown_fingerprint_exits_1(self, runner: CliRunner, mem_env) -> None:
        res = runner.invoke(
            app,
            [
                "device",
                "register",
                "--fingerprint",
                "0" * 32,
                "--device-id",
                "my-dev",
            ],
        )
        assert res.exit_code == 1
        assert "Claim failed" in res.stdout


class TestDeviceInstallUdevRulesCli:
    def test_udev_rules_print_to_stdout(self, runner: CliRunner, mem_env, tmp_path: Path) -> None:
        out = tmp_path / "rules.txt"
        # Use --output instead of --apply so we don't need sudo
        res = runner.invoke(
            app,
            [
                "device",
                "install-udev-rules",
                "--output",
                str(out),
            ],
        )
        assert res.exit_code == 0
        assert out.exists()
        content = out.read_text()
        assert "Auto-generated by HIVE" in content

    def test_udev_rules_apply_default_path_writes(self, runner: CliRunner, mem_env) -> None:
        # We can't actually write to /etc without sudo; we just verify
        # the command exists and prints an error.
        res = runner.invoke(app, ["device", "install-udev-rules", "--apply"])
        # Either exit 0 (in docker/root) or exit 1 with permission message
        assert res.exit_code in (0, 1)


class TestLockSweepCli:
    def test_lock_sweep_runs(self, runner: CliRunner, mem_env) -> None:
        res = runner.invoke(app, ["lock", "sweep"])
        assert res.exit_code == 0
        assert "Swept" in res.stdout

    def test_lock_sweep_json(self, runner: CliRunner, mem_env) -> None:
        import json

        res = runner.invoke(app, ["lock", "sweep", "--json"])
        assert res.exit_code == 0
        data = json.loads(res.stdout)
        assert "removed" in data


class TestLockListSqliteCli:
    def test_lock_list_sqlite_empty(self, runner: CliRunner, mem_env) -> None:
        res = runner.invoke(app, ["lock", "list", "--sqlite"])
        assert res.exit_code == 0
        assert "Active Locks (0)" in res.stdout
